### 회원 가입 API
POST http://localhost:8081/api/v1/member
Content-Type: application/json

{
  "email": "youngjun108059@gmail.com",
  "password": "1234",
  "name": "박영준",
  "phone": "010-1234-5678",
  "nickname": "만두",
  "area": "판교"
}

### 로그인 API
POST http://localhost:8081/api/v1/login
Content-Type: application/json

{
  "email": "youngjun108059@gmail.com",
  "password": "1234"
}
