### 상품 등록 API 1
POST http://localhost:8081/api/v1/product
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "한남더힐 100평 펜트하우스 매매",
  "areaId": "1",
  "categoryId": "1",
  "price": 30000000000,
  "content": "300억에 급매합니다 ^^",
  "imageList": [
    "https://pds.joongang.co.kr/news/component/htmlphoto_mmdata/201708/05/b313969a-a073-4665-a721-8af77dc1df39.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5jkEhvHzwrYaHXjVrGlXpFZXgruTkZnEiqGkbg3hYVSTW9rYtZrQQhkurXgG7UkKNSO0&usqp=CAU"
  ]
}

### 상품 등록 API 2
POST http://localhost:8081/api/v1/product
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "롤스로이스 팬텀 팝니다",
  "areaId": "2",
  "categoryId": "2",
  "price": 760000000,
  "content": "쿨거 5,000원 DC",
  "imageList": [
    "https://www.motoya.co.kr/news/photo/202205/35313_220048_1952.jpg",
    "https://image-cdn.hypb.st/https%3A%2F%2Fkr.hypebeast.com%2Ffiles%2F2021%2F02%2Frolls-royce-the-koa-phantom-commission-luxury-car-image-tw.jpg?w=960&cbr=1&q=90&fit=max"
  ]
}

### 상품 등록 API 3
POST http://localhost:8081/api/v1/product
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "당근 인형 팔아요",
  "areaId": "1",
  "categoryId": "2",
  "price": 50000,
  "content": "택포하면 60만원",
  "imageList": [
    "http://img.insight.co.kr/static/2018/09/14/700/0iv2a3d7431y91a0k74u.jpg",
    "https://mblogthumb-phinf.pstatic.net/MjAxODEwMTVfMzMg/MDAxNTM5NTgxNjg4NjMz.2z1o0PIol0k9nsYbIv-qsyziByI5ikd3lT9HNjh_HwYg.OhTZ1HYfZvYYZu9ORTG5C4GbynDW5OtYtXhoAt_sUVwg.JPEG.jiyi94/image_8531766581539581679066.jpg?type=w800"
  ]
}

### 상품리스트 조회
GET http://localhost:8081/api/v1/product/list
Authorization: Bearer {{TOKEN}}

### 상품 단건 조회 API
GET http://localhost:8081/api/v1/product?product_id=1
Authorization: Bearer {{TOKEN}}

# Response
#{
#  "imagePaths": [
#    "https://pds.joongang.co.kr/news/component/htmlphoto_mmdata/201708/05/b313969a-a073-4665-a721-8af77dc1df39.jpg",
#    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5jkEhvHzwrYaHXjVrGlXpFZXgruTkZnEiqGkbg3hYVSTW9rYtZrQQhkurXgG7UkKNSO0&usqp=CAU"
#  ],
#  "imagePathCount": 2,
#  "nickname": "개발하는 만두",
#  "title": "한남더힐 100평 펜트하우스 매매",
#  "price": 30000000000,
#  "category": "디지털기기",
#  "createAt": "2023-01-22 00:26:12",
#  "content": "300억에 급매합니다 ^^",
#  "chatCount": 0,
#  "likesCount": 0
#}

### 상품 삭제 API
DELETE http://localhost:8081/api/v1/product?product_id=1
Authorization: Bearer {{TOKEN}}

### 상품 수정 API
PUT http://localhost:8081/api/v1/product
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "id": 3,
  "title": "당근 인형 팔아요(수정)",
  "categoryId": "1",
  "price": 234000,
  "content": "택포하면 2000만원",
  "status": "RESERVED",
  "imageList": [
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtEZnrIpn-1h19MsYCvh9y9Sss-HCrNBRCLLJV2e1Td06uurM2-dBs9BfabEhG0aFqkdE&usqp=CAU",
    "https://img.seoul.co.kr/img/upload/2018/06/11/SSI_20180611134927_O2.jpg",
    "http://storage.enuri.info/pic_upload/knowbox2/202008/1235090782020082406ccecf4-a8fc-41c7-92a5-1146e0ce4189.gif"
  ]
}

### 상품 등록 API 4
POST http://localhost:8081/api/v1/product
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "카테고리 필터 테스트를 해볼거야",
  "areaId": "1",
  "categoryId": "3",
  "price": 470,
  "content": "카테고리 3",
  "imageList": [
    "https://pds.joongang.co.kr/news/component/htmlphoto_mmdata/201708/05/b313969a-a073-4665-a721-8af77dc1df39.jpg"
  ]
}

### 상품리스트 조회 (카테고리별 조회)
GET http://localhost:8081/api/v1/product/list?category_id=1
Authorization: Bearer {{TOKEN}}

### 상품리스트 조회 (상품 상태별 조회)
GET http://localhost:8081/api/v1/product/list?member_id=1&status=TRADING
Authorization: Bearer {{TOKEN}}

### 상품리스트 조회 (상품 상태별 조회 2)
GET http://localhost:8081/api/v1/product/list?member_id=1&status=RESERVED
Authorization: Bearer {{TOKEN}}

### 상품리스트 조회 (특정회원 + 좋아요 + 거래상태)
GET http://localhost:8081/api/v1/product/list?member_id=1&likes=true&status=TRADING
Authorization: Bearer {{TOKEN}}

### 상품리스트 조회 (검색)
GET http://localhost:8081/api/v1/product/list?search=당근
Authorization: Bearer {{TOKEN}}